version: '3.9'

services:

  backend:
    build: ./backend
    container_name: fakedetect-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=super-secret-dev-key-change-me
      - DEBUG=True
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: fakedetect-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules        # keep container node_modules isolated
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000

  app:
    build: .
    image: thetanishdewase1/fake_product_identifier:v1.0
